<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://mamwfe-pkg.mam.foxtel.com.au:8080/fx-FSAdapter/rest/fs/selectMostRecent" ID="_fNXWwPgqEeKeqe51R6X2ag">
  <rest:operation verb="PUT" name="rhozetSelectMostRecent" ID="_fNXWwfgqEeKeqe51R6X2ag">
    <rest:input type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="body" headerDirection="request" contentType="text/plain" ID="_fNXWwvgqEeKeqe51R6X2ag"/>
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}boolean" name="response" headerDirection="request" contentType="text/plain" ID="_fNXWw_gqEeKeqe51R6X2ag"/>
  </rest:operation>
</rest:descriptor>