package com.mediasmiths.mayam;

public enum MayamTaskListType {
	INGEST,
	INGEST_FAILURE,
	MY_WORKLIST,
	QC_VIEW,
	QC_WARNING,
	PREVIEW,
	PREVIEW_FURTHER_ANALYSIS,
	COMPLIANCE_LOGGING,
	COMPLIANCE_EDIT,
	UNMATCHED_MEDIA,
	FIX_STITCH_EDIT,
	SEGMENTATION,
	TX_DELIVERY,
	TX_DELIVERY_FAILURE,
	PURGE_CANDIDATE_LIST,
	GENERIC_TASK_ERROR,
	EXTENDED_PUBLISHING,
	THIRD_PARTY,
	ASSOCIATED_TASKS
}
