package com.mediasmiths.mayam;

public enum MayamClientErrorCode {
	SUCCESS,
	NOT_IMPLEMENTED,
	FAILURE, 
	TITLE_CREATION_FAILED, 
	TITLE_METADATA_UNAVAILABLE, 
	MAYAM_EXCEPTION, 
	TITLE_UPDATE_FAILED, 
	MATERIAL_CREATION_FAILED,
	MATERIAL_UPDATE_FAILED, 
	PACKAGE_CREATION_FAILED,
	PACKAGE_UPDATE_FAILED,
	TITLE_UNAVAILABLE,
	PACKAGE_UNAVAILABLE,
	MATERIAL_UNAVAILABLE,
	TITLE_FIND_FAILED,
	MATERIAL_FIND_FAILED,
	PACKAGE_FIND_FAILED
}
