#!/bin/sh
### BEGIN INIT INFO
# Provides:          tomcat
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Apache Tomcat Launcher
# Description:       Launches tomcat
### END INIT INFO

# Author: Peter Wright

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
TOMCAT_DIR="/opt/ipwf/applications/apache-tomcat-7.0.32"

case "$1" in
  debug)
	exec "$TOMCAT_DIR/bin/debug.sh"
	;;
  start|restart|force-reload)
	exec "$TOMCAT_DIR/bin/start.sh"
	;;
  stop)
	exec "$TOMCAT_DIR/bin/stop.sh"
	;;
  kill)
	exec "$TOMCAT_DIR/bin/kill.sh"
	;;
  status)
	exec "$TOMCAT_DIR/bin/status.sh"
       ;;
  *)
	echo "Usage: $SCRIPTNAME {debug|start|stop|kill|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
