<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://mamwfe-pkg.mam.foxtel.com.au:8080/fx-TcAdapter/transcoder/job/{guid}/priority?priority={priority}" ID="_k475IGk1EeKkF6Cl22xM4g">
  <rest:operation verb="GET" name="setPriority" ID="_k475JGk1EeKkF6Cl22xM4g">
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}anyType" name="response" headerDirection="request" contentType="text/xml" ID="_ub3iIKalEeKCpI3wQsthIA"/>
  </rest:operation>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="guid" headerDirection="request" contentType="text/xml" ID="_nkPo0Gk1EeKkF6Cl22xM4g"/>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}int" name="priority" headerDirection="request" contentType="text/xml" ID="_57iDYKalEeKCpI3wQsthIA"/>
</rest:descriptor>