//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 01:44:29 PM BST 
//


package events.common.ip.foxtel.mediasmiths.com._001._000;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A type to represent an ArdomeJobFailure event
 *                 
 * 
 * <p>Java class for autoQCFullResultNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="autoQCFullResultNotification">
 *   &lt;complexContent>
 *     &lt;extension base="{http://com.mediasmiths.foxtel.ip.common.events/001/000}IPEvent">
 *       &lt;sequence>
 *         &lt;element name="assetId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jobId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="materialID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="forTXDelivery" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="channels" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taskStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qcStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taskStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taskFinish" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="warningTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="manualOverride" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="titleLength" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "autoQCFullResultNotification", propOrder = {
    "assetId",
    "jobId",
    "materialID",
    "forTXDelivery",
    "title",
    "channels",
    "contentType",
    "operator",
    "taskStatus",
    "qcStatus",
    "taskStart",
    "taskFinish",
    "warningTime",
    "manualOverride",
    "titleLength"
})
public class AutoQCFullResultNotification
    extends IPEvent
{

    @XmlElement(required = true)
    protected String assetId;
    @XmlElement(required = true)
    protected String jobId;
    @XmlElement(required = true)
    protected String materialID;
    protected boolean forTXDelivery;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String channels;
    @XmlElement(required = true)
    protected String contentType;
    @XmlElement(required = true)
    protected String operator;
    @XmlElement(required = true)
    protected String taskStatus;
    @XmlElement(required = true)
    protected String qcStatus;
    @XmlElement(required = true)
    protected String taskStart;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar taskFinish;
    @XmlElement(required = true)
    protected String warningTime;
    @XmlElement(required = true)
    protected String manualOverride;
    @XmlElement(required = true)
    protected String titleLength;

    /**
     * Gets the value of the assetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetId() {
        return assetId;
    }

    /**
     * Sets the value of the assetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetId(String value) {
        this.assetId = value;
    }

    /**
     * Gets the value of the jobId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * Sets the value of the jobId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobId(String value) {
        this.jobId = value;
    }

    /**
     * Gets the value of the materialID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialID() {
        return materialID;
    }

    /**
     * Sets the value of the materialID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialID(String value) {
        this.materialID = value;
    }

    /**
     * Gets the value of the forTXDelivery property.
     * 
     */
    public boolean isForTXDelivery() {
        return forTXDelivery;
    }

    /**
     * Sets the value of the forTXDelivery property.
     * 
     */
    public void setForTXDelivery(boolean value) {
        this.forTXDelivery = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the channels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannels() {
        return channels;
    }

    /**
     * Sets the value of the channels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannels(String value) {
        this.channels = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the taskStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * Sets the value of the taskStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskStatus(String value) {
        this.taskStatus = value;
    }

    /**
     * Gets the value of the qcStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQcStatus() {
        return qcStatus;
    }

    /**
     * Sets the value of the qcStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQcStatus(String value) {
        this.qcStatus = value;
    }

    /**
     * Gets the value of the taskStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskStart() {
        return taskStart;
    }

    /**
     * Sets the value of the taskStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskStart(String value) {
        this.taskStart = value;
    }

    /**
     * Gets the value of the taskFinish property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTaskFinish() {
        return taskFinish;
    }

    /**
     * Sets the value of the taskFinish property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTaskFinish(XMLGregorianCalendar value) {
        this.taskFinish = value;
    }

    /**
     * Gets the value of the warningTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarningTime() {
        return warningTime;
    }

    /**
     * Sets the value of the warningTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarningTime(String value) {
        this.warningTime = value;
    }

    /**
     * Gets the value of the manualOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManualOverride() {
        return manualOverride;
    }

    /**
     * Sets the value of the manualOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManualOverride(String value) {
        this.manualOverride = value;
    }

    /**
     * Gets the value of the titleLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleLength() {
        return titleLength;
    }

    /**
     * Sets the value of the titleLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleLength(String value) {
        this.titleLength = value;
    }

}
