//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 01:44:29 PM BST 
//


package events.common.ip.foxtel.mediasmiths.com._001._000;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://com.mediasmiths.foxtel.ip.common.events/001/000}IPEvent">
 *       &lt;sequence>
 *         &lt;element name="materialID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assetTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taskStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qcStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taskStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="taskFinish" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="warningTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="overriden" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="failureParameter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "materialID",
    "assetTitle",
    "contentType",
    "operator",
    "taskStatus",
    "qcStatus",
    "taskStart",
    "taskFinish",
    "warningTime",
    "overriden",
    "failureParameter"
})
@XmlRootElement(name = "AutoQCEvent")
public class AutoQCEvent
    extends IPEvent
{

    @XmlElement(required = true)
    protected String materialID;
    @XmlElement(required = true)
    protected String assetTitle;
    @XmlElement(required = true)
    protected String contentType;
    @XmlElement(required = true)
    protected String operator;
    @XmlElement(required = true)
    protected String taskStatus;
    @XmlElement(required = true)
    protected String qcStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar taskStart;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar taskFinish;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar warningTime;
    protected Boolean overriden;
    protected String failureParameter;

    /**
     * Gets the value of the materialID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialID() {
        return materialID;
    }

    /**
     * Sets the value of the materialID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialID(String value) {
        this.materialID = value;
    }

    /**
     * Gets the value of the assetTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetTitle() {
        return assetTitle;
    }

    /**
     * Sets the value of the assetTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetTitle(String value) {
        this.assetTitle = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the taskStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * Sets the value of the taskStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskStatus(String value) {
        this.taskStatus = value;
    }

    /**
     * Gets the value of the qcStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQcStatus() {
        return qcStatus;
    }

    /**
     * Sets the value of the qcStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQcStatus(String value) {
        this.qcStatus = value;
    }

    /**
     * Gets the value of the taskStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTaskStart() {
        return taskStart;
    }

    /**
     * Sets the value of the taskStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTaskStart(XMLGregorianCalendar value) {
        this.taskStart = value;
    }

    /**
     * Gets the value of the taskFinish property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTaskFinish() {
        return taskFinish;
    }

    /**
     * Sets the value of the taskFinish property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTaskFinish(XMLGregorianCalendar value) {
        this.taskFinish = value;
    }

    /**
     * Gets the value of the warningTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWarningTime() {
        return warningTime;
    }

    /**
     * Sets the value of the warningTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWarningTime(XMLGregorianCalendar value) {
        this.warningTime = value;
    }

    /**
     * Gets the value of the overriden property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOverriden() {
        return overriden;
    }

    /**
     * Sets the value of the overriden property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOverriden(Boolean value) {
        this.overriden = value;
    }

    /**
     * Gets the value of the failureParameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailureParameter() {
        return failureParameter;
    }

    /**
     * Sets the value of the failureParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailureParameter(String value) {
        this.failureParameter = value;
    }

}
