//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 01:44:29 PM BST 
//


package events.common.ip.foxtel.mediasmiths.com._001._000;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://com.mediasmiths.foxtel.ip.common.events/001/000}IPEvent">
 *       &lt;sequence>
 *         &lt;element name="dateRange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="materialId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="channels" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taskStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taskStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taskFinish" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="externalCompliance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MasterID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TitleField" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Loggerdetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emailaddresses" type="{http://com.mediasmiths.foxtel.ip.common.events/001/000}emailaddresses"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dateRange",
    "title",
    "materialId",
    "channels",
    "taskStatus",
    "taskStart",
    "taskFinish",
    "externalCompliance",
    "masterID",
    "titleField",
    "loggerdetails",
    "emailaddresses"
})
@XmlRootElement(name = "ComplianceLoggingMarker")
public class ComplianceLoggingMarker
    extends IPEvent
{

    @XmlElement(required = true)
    protected String dateRange;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String materialId;
    @XmlElement(required = true)
    protected String channels;
    @XmlElement(required = true)
    protected String taskStatus;
    @XmlElement(required = true)
    protected String taskStart;
    @XmlElement(required = true)
    protected String taskFinish;
    @XmlElement(required = true)
    protected String externalCompliance;
    @XmlElement(name = "MasterID", required = true)
    protected String masterID;
    @XmlElement(name = "TitleField", required = true)
    protected String titleField;
    @XmlElement(name = "Loggerdetails", required = true)
    protected String loggerdetails;
    @XmlElement(required = true)
    protected Emailaddresses emailaddresses;

    /**
     * Gets the value of the dateRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateRange(String value) {
        this.dateRange = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the materialId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialId() {
        return materialId;
    }

    /**
     * Sets the value of the materialId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialId(String value) {
        this.materialId = value;
    }

    /**
     * Gets the value of the channels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannels() {
        return channels;
    }

    /**
     * Sets the value of the channels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannels(String value) {
        this.channels = value;
    }

    /**
     * Gets the value of the taskStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * Sets the value of the taskStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskStatus(String value) {
        this.taskStatus = value;
    }

    /**
     * Gets the value of the taskStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskStart() {
        return taskStart;
    }

    /**
     * Sets the value of the taskStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskStart(String value) {
        this.taskStart = value;
    }

    /**
     * Gets the value of the taskFinish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskFinish() {
        return taskFinish;
    }

    /**
     * Sets the value of the taskFinish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskFinish(String value) {
        this.taskFinish = value;
    }

    /**
     * Gets the value of the externalCompliance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalCompliance() {
        return externalCompliance;
    }

    /**
     * Sets the value of the externalCompliance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalCompliance(String value) {
        this.externalCompliance = value;
    }

    /**
     * Gets the value of the masterID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterID() {
        return masterID;
    }

    /**
     * Sets the value of the masterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterID(String value) {
        this.masterID = value;
    }

    /**
     * Gets the value of the titleField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleField() {
        return titleField;
    }

    /**
     * Sets the value of the titleField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleField(String value) {
        this.titleField = value;
    }

    /**
     * Gets the value of the loggerdetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoggerdetails() {
        return loggerdetails;
    }

    /**
     * Sets the value of the loggerdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoggerdetails(String value) {
        this.loggerdetails = value;
    }

    /**
     * Gets the value of the emailaddresses property.
     * 
     * @return
     *     possible object is
     *     {@link Emailaddresses }
     *     
     */
    public Emailaddresses getEmailaddresses() {
        return emailaddresses;
    }

    /**
     * Sets the value of the emailaddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Emailaddresses }
     *     
     */
    public void setEmailaddresses(Emailaddresses value) {
        this.emailaddresses = value;
    }

}
