//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 01:44:29 PM BST 
//


package events.common.ip.foxtel.mediasmiths.com._001._000;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Used to store daily disk usage report
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://com.mediasmiths.foxtel.ip.common.events/001/000}IPEvent">
 *       &lt;sequence>
 *         &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hrSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tsmSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lrSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="othersSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "channel",
    "hrSize",
    "tsmSize",
    "lrSize",
    "othersSize",
    "totalSize",
    "date"
})
@XmlRootElement(name = "DiskUsageEvent")
public class DiskUsageEvent
    extends IPEvent
{

    @XmlElement(required = true)
    protected String channel;
    @XmlElement(required = true)
    protected String hrSize;
    @XmlElement(required = true)
    protected String tsmSize;
    @XmlElement(required = true)
    protected String lrSize;
    @XmlElement(required = true)
    protected String othersSize;
    @XmlElement(required = true)
    protected String totalSize;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannel(String value) {
        this.channel = value;
    }

    /**
     * Gets the value of the hrSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHrSize() {
        return hrSize;
    }

    /**
     * Sets the value of the hrSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHrSize(String value) {
        this.hrSize = value;
    }

    /**
     * Gets the value of the tsmSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTsmSize() {
        return tsmSize;
    }

    /**
     * Sets the value of the tsmSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTsmSize(String value) {
        this.tsmSize = value;
    }

    /**
     * Gets the value of the lrSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrSize() {
        return lrSize;
    }

    /**
     * Sets the value of the lrSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrSize(String value) {
        this.lrSize = value;
    }

    /**
     * Gets the value of the othersSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOthersSize() {
        return othersSize;
    }

    /**
     * Sets the value of the othersSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOthersSize(String value) {
        this.othersSize = value;
    }

    /**
     * Gets the value of the totalSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalSize() {
        return totalSize;
    }

    /**
     * Sets the value of the totalSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalSize(String value) {
        this.totalSize = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

}
