//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 01:44:29 PM BST 
//


package events.common.ip.foxtel.mediasmiths.com._001._000;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * The root type for events about the IP service
 * 				infrastructure.
 * 			
 * 
 * <p>Java class for IPEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="channelGroup" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="attachments" type="{http://com.mediasmiths.foxtel.ip.common.events/001/000}eventAttachment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPEvent", propOrder = {
    "channelGroup",
    "attachments"
})
@XmlSeeAlso({
    FilePickupDetails.class,
    QcServerFail.class,
    AutoQCFullResultNotification.class,
    AutoQCRequest.class,
    ErrorReport.class,
    MediaPickupNotification.class,
    ExtendedPublishingTaskEvent.class,
    AddOrUpdateMaterial.class,
    AutoQCEvent.class,
    ComplianceLoggingTaskEvent.class,
    MediaPickupQuarantineNotification.class,
    PurgeNotification.class,
    PickupNotification.class,
    IBMSDeleteItemFailure.class,
    DiskUsageEvent.class,
    Export.class,
    ArdomeJobFailure.class,
    AggregatedBMS.class,
    ExportStart.class,
    ManualQANotification.class,
    CreationComplete.class,
    PurgeEventNotification.class,
    TxMoveFailure.class,
    StorageUsageDetails.class,
    TcEvent.class,
    ArdomeImportFailure.class,
    TxDelivered.class,
    ContentAvailable.class,
    PurgeMessage.class,
    AutoQCNotification.class,
    PreviewEventDetail.class,
    ComplianceLoggingMarker.class,
    ChannelConditionsFound.class,
    PurgeMaterial.class,
    PurgePackage.class,
    AutoQCResultNotification.class,
    CreateOrUpdateTitle.class,
    CommFailure.class,
    AddOrUpdatePackage.class
})
public class IPEvent {

    protected List<String> channelGroup;
    protected List<EventAttachment> attachments;

    /**
     * Gets the value of the channelGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channelGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannelGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getChannelGroup() {
        if (channelGroup == null) {
            channelGroup = new ArrayList<String>();
        }
        return this.channelGroup;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventAttachment }
     * 
     * 
     */
    public List<EventAttachment> getAttachments() {
        if (attachments == null) {
            attachments = new ArrayList<EventAttachment>();
        }
        return this.attachments;
    }

}
