//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 01:44:29 PM BST 
//


package events.common.ip.foxtel.mediasmiths.com._001._000;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://com.mediasmiths.foxtel.ip.common.events/001/000}IPEvent">
 *       &lt;sequence>
 *         &lt;element name="dateRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="materialID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="channels" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aggregatorID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taskStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="previewStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hrPreview" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hrPreviewRequested" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="escalated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timeEscalated" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="titleLength" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reordered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dateRange",
    "title",
    "materialID",
    "channels",
    "operator",
    "aggregatorID",
    "taskStatus",
    "previewStatus",
    "hrPreview",
    "hrPreviewRequested",
    "escalated",
    "timeEscalated",
    "titleLength",
    "reordered"
})
@XmlRootElement(name = "ManualQANotification")
public class ManualQANotification
    extends IPEvent
{

    protected String dateRange;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String materialID;
    @XmlElement(required = true)
    protected String channels;
    @XmlElement(required = true)
    protected String operator;
    @XmlElement(required = true)
    protected String aggregatorID;
    @XmlElement(required = true)
    protected String taskStatus;
    @XmlElement(required = true)
    protected String previewStatus;
    @XmlElement(required = true)
    protected String hrPreview;
    @XmlElement(required = true)
    protected String hrPreviewRequested;
    protected String escalated;
    @XmlElement(required = true)
    protected String timeEscalated;
    @XmlElement(required = true)
    protected String titleLength;
    protected String reordered;

    /**
     * Gets the value of the dateRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateRange(String value) {
        this.dateRange = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the materialID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialID() {
        return materialID;
    }

    /**
     * Sets the value of the materialID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialID(String value) {
        this.materialID = value;
    }

    /**
     * Gets the value of the channels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannels() {
        return channels;
    }

    /**
     * Sets the value of the channels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannels(String value) {
        this.channels = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the aggregatorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAggregatorID() {
        return aggregatorID;
    }

    /**
     * Sets the value of the aggregatorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAggregatorID(String value) {
        this.aggregatorID = value;
    }

    /**
     * Gets the value of the taskStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * Sets the value of the taskStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskStatus(String value) {
        this.taskStatus = value;
    }

    /**
     * Gets the value of the previewStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviewStatus() {
        return previewStatus;
    }

    /**
     * Sets the value of the previewStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviewStatus(String value) {
        this.previewStatus = value;
    }

    /**
     * Gets the value of the hrPreview property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHrPreview() {
        return hrPreview;
    }

    /**
     * Sets the value of the hrPreview property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHrPreview(String value) {
        this.hrPreview = value;
    }

    /**
     * Gets the value of the hrPreviewRequested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHrPreviewRequested() {
        return hrPreviewRequested;
    }

    /**
     * Sets the value of the hrPreviewRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHrPreviewRequested(String value) {
        this.hrPreviewRequested = value;
    }

    /**
     * Gets the value of the escalated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEscalated() {
        return escalated;
    }

    /**
     * Sets the value of the escalated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEscalated(String value) {
        this.escalated = value;
    }

    /**
     * Gets the value of the timeEscalated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeEscalated() {
        return timeEscalated;
    }

    /**
     * Sets the value of the timeEscalated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeEscalated(String value) {
        this.timeEscalated = value;
    }

    /**
     * Gets the value of the titleLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleLength() {
        return titleLength;
    }

    /**
     * Sets the value of the titleLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleLength(String value) {
        this.titleLength = value;
    }

    /**
     * Gets the value of the reordered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReordered() {
        return reordered;
    }

    /**
     * Sets the value of the reordered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReordered(String value) {
        this.reordered = value;
    }

}
