//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 01:44:29 PM BST 
//


package events.common.ip.foxtel.mediasmiths.com._001._000;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the events.common.ip.foxtel.mediasmiths.com._001._000 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AutoQCErrorNotificationFailureParameter_QNAME = new QName("http://com.mediasmiths.foxtel.ip.common.events/001/000", "failureParameter");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: events.common.ip.foxtel.mediasmiths.com._001._000
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddOrUpdatePackage }
     * 
     */
    public AddOrUpdatePackage createAddOrUpdatePackage() {
        return new AddOrUpdatePackage();
    }

    /**
     * Create an instance of {@link IPEvent }
     * 
     */
    public IPEvent createIPEvent() {
        return new IPEvent();
    }

    /**
     * Create an instance of {@link EventAttachment }
     * 
     */
    public EventAttachment createEventAttachment() {
        return new EventAttachment();
    }

    /**
     * Create an instance of {@link CommFailure }
     * 
     */
    public CommFailure createCommFailure() {
        return new CommFailure();
    }

    /**
     * Create an instance of {@link CreateOrUpdateTitle }
     * 
     */
    public CreateOrUpdateTitle createCreateOrUpdateTitle() {
        return new CreateOrUpdateTitle();
    }

    /**
     * Create an instance of {@link AutoQCFailureNotification }
     * 
     */
    public AutoQCFailureNotification createAutoQCFailureNotification() {
        return new AutoQCFailureNotification();
    }

    /**
     * Create an instance of {@link AutoQCResultNotification }
     * 
     */
    public AutoQCResultNotification createAutoQCResultNotification() {
        return new AutoQCResultNotification();
    }

    /**
     * Create an instance of {@link PurgePackage }
     * 
     */
    public PurgePackage createPurgePackage() {
        return new PurgePackage();
    }

    /**
     * Create an instance of {@link PurgeMaterial }
     * 
     */
    public PurgeMaterial createPurgeMaterial() {
        return new PurgeMaterial();
    }

    /**
     * Create an instance of {@link ChannelConditionsFound }
     * 
     */
    public ChannelConditionsFound createChannelConditionsFound() {
        return new ChannelConditionsFound();
    }

    /**
     * Create an instance of {@link ComplianceLoggingMarker }
     * 
     */
    public ComplianceLoggingMarker createComplianceLoggingMarker() {
        return new ComplianceLoggingMarker();
    }

    /**
     * Create an instance of {@link Emailaddresses }
     * 
     */
    public Emailaddresses createEmailaddresses() {
        return new Emailaddresses();
    }

    /**
     * Create an instance of {@link PreviewEventDetail }
     * 
     */
    public PreviewEventDetail createPreviewEventDetail() {
        return new PreviewEventDetail();
    }

    /**
     * Create an instance of {@link AutoQCNotification }
     * 
     */
    public AutoQCNotification createAutoQCNotification() {
        return new AutoQCNotification();
    }

    /**
     * Create an instance of {@link PurgeTitle }
     * 
     */
    public PurgeTitle createPurgeTitle() {
        return new PurgeTitle();
    }

    /**
     * Create an instance of {@link PurgeMessage }
     * 
     */
    public PurgeMessage createPurgeMessage() {
        return new PurgeMessage();
    }

    /**
     * Create an instance of {@link ContentAvailable }
     * 
     */
    public ContentAvailable createContentAvailable() {
        return new ContentAvailable();
    }

    /**
     * Create an instance of {@link TxDelivered }
     * 
     */
    public TxDelivered createTxDelivered() {
        return new TxDelivered();
    }

    /**
     * Create an instance of {@link ArdomeImportFailure }
     * 
     */
    public ArdomeImportFailure createArdomeImportFailure() {
        return new ArdomeImportFailure();
    }

    /**
     * Create an instance of {@link TcEvent }
     * 
     */
    public TcEvent createTcEvent() {
        return new TcEvent();
    }

    /**
     * Create an instance of {@link StorageUsageDetails }
     * 
     */
    public StorageUsageDetails createStorageUsageDetails() {
        return new StorageUsageDetails();
    }

    /**
     * Create an instance of {@link TxMoveFailure }
     * 
     */
    public TxMoveFailure createTxMoveFailure() {
        return new TxMoveFailure();
    }

    /**
     * Create an instance of {@link AutoQCErrorNotification }
     * 
     */
    public AutoQCErrorNotification createAutoQCErrorNotification() {
        return new AutoQCErrorNotification();
    }

    /**
     * Create an instance of {@link PreviewFailed }
     * 
     */
    public PreviewFailed createPreviewFailed() {
        return new PreviewFailed();
    }

    /**
     * Create an instance of {@link PurgeEventNotification }
     * 
     */
    public PurgeEventNotification createPurgeEventNotification() {
        return new PurgeEventNotification();
    }

    /**
     * Create an instance of {@link CreationComplete }
     * 
     */
    public CreationComplete createCreationComplete() {
        return new CreationComplete();
    }

    /**
     * Create an instance of {@link ManualQANotification }
     * 
     */
    public ManualQANotification createManualQANotification() {
        return new ManualQANotification();
    }

    /**
     * Create an instance of {@link ExportStart }
     * 
     */
    public ExportStart createExportStart() {
        return new ExportStart();
    }

    /**
     * Create an instance of {@link AggregatedBMS }
     * 
     */
    public AggregatedBMS createAggregatedBMS() {
        return new AggregatedBMS();
    }

    /**
     * Create an instance of {@link ArdomeJobFailure }
     * 
     */
    public ArdomeJobFailure createArdomeJobFailure() {
        return new ArdomeJobFailure();
    }

    /**
     * Create an instance of {@link Export }
     * 
     */
    public Export createExport() {
        return new Export();
    }

    /**
     * Create an instance of {@link DiskUsageEvent }
     * 
     */
    public DiskUsageEvent createDiskUsageEvent() {
        return new DiskUsageEvent();
    }

    /**
     * Create an instance of {@link IBMSDeleteItemFailure }
     * 
     */
    public IBMSDeleteItemFailure createIBMSDeleteItemFailure() {
        return new IBMSDeleteItemFailure();
    }

    /**
     * Create an instance of {@link PickupNotification }
     * 
     */
    public PickupNotification createPickupNotification() {
        return new PickupNotification();
    }

    /**
     * Create an instance of {@link FilePickupDetails }
     * 
     */
    public FilePickupDetails createFilePickupDetails() {
        return new FilePickupDetails();
    }

    /**
     * Create an instance of {@link ManualPurge }
     * 
     */
    public ManualPurge createManualPurge() {
        return new ManualPurge();
    }

    /**
     * Create an instance of {@link PurgeNotification }
     * 
     */
    public PurgeNotification createPurgeNotification() {
        return new PurgeNotification();
    }

    /**
     * Create an instance of {@link AutoQCPassNotification }
     * 
     */
    public AutoQCPassNotification createAutoQCPassNotification() {
        return new AutoQCPassNotification();
    }

    /**
     * Create an instance of {@link MediaPickupQuarantineNotification }
     * 
     */
    public MediaPickupQuarantineNotification createMediaPickupQuarantineNotification() {
        return new MediaPickupQuarantineNotification();
    }

    /**
     * Create an instance of {@link ProtectedPurgeFail }
     * 
     */
    public ProtectedPurgeFail createProtectedPurgeFail() {
        return new ProtectedPurgeFail();
    }

    /**
     * Create an instance of {@link ComplianceLoggingTaskEvent }
     * 
     */
    public ComplianceLoggingTaskEvent createComplianceLoggingTaskEvent() {
        return new ComplianceLoggingTaskEvent();
    }

    /**
     * Create an instance of {@link AutoQCEvent }
     * 
     */
    public AutoQCEvent createAutoQCEvent() {
        return new AutoQCEvent();
    }

    /**
     * Create an instance of {@link AddOrUpdateMaterial }
     * 
     */
    public AddOrUpdateMaterial createAddOrUpdateMaterial() {
        return new AddOrUpdateMaterial();
    }

    /**
     * Create an instance of {@link ExtendedPublishingTaskEvent }
     * 
     */
    public ExtendedPublishingTaskEvent createExtendedPublishingTaskEvent() {
        return new ExtendedPublishingTaskEvent();
    }

    /**
     * Create an instance of {@link MediaPickupNotification }
     * 
     */
    public MediaPickupNotification createMediaPickupNotification() {
        return new MediaPickupNotification();
    }

    /**
     * Create an instance of {@link ErrorReport }
     * 
     */
    public ErrorReport createErrorReport() {
        return new ErrorReport();
    }

    /**
     * Create an instance of {@link QcServerFail }
     * 
     */
    public QcServerFail createQcServerFail() {
        return new QcServerFail();
    }

    /**
     * Create an instance of {@link AutoQCFullResultNotification }
     * 
     */
    public AutoQCFullResultNotification createAutoQCFullResultNotification() {
        return new AutoQCFullResultNotification();
    }

    /**
     * Create an instance of {@link MaterialTransferForTCResponse }
     * 
     */
    public MaterialTransferForTCResponse createMaterialTransferForTCResponse() {
        return new MaterialTransferForTCResponse();
    }

    /**
     * Create an instance of {@link InvokeIntalioTXFlow }
     * 
     */
    public InvokeIntalioTXFlow createInvokeIntalioTXFlow() {
        return new InvokeIntalioTXFlow();
    }

    /**
     * Create an instance of {@link MaterialTransferForTCRequest }
     * 
     */
    public MaterialTransferForTCRequest createMaterialTransferForTCRequest() {
        return new MaterialTransferForTCRequest();
    }

    /**
     * Create an instance of {@link AssetTransferForQCResponse }
     * 
     */
    public AssetTransferForQCResponse createAssetTransferForQCResponse() {
        return new AssetTransferForQCResponse();
    }

    /**
     * Create an instance of {@link ContentPickup }
     * 
     */
    public ContentPickup createContentPickup() {
        return new ContentPickup();
    }

    /**
     * Create an instance of {@link InvokeIntalioTCFlow }
     * 
     */
    public InvokeIntalioTCFlow createInvokeIntalioTCFlow() {
        return new InvokeIntalioTCFlow();
    }

    /**
     * Create an instance of {@link GetQCProfileResponse }
     * 
     */
    public GetQCProfileResponse createGetQCProfileResponse() {
        return new GetQCProfileResponse();
    }

    /**
     * Create an instance of {@link AssetTransferForQCRequest }
     * 
     */
    public AssetTransferForQCRequest createAssetTransferForQCRequest() {
        return new AssetTransferForQCRequest();
    }

    /**
     * Create an instance of {@link InvokeIntalioQCFlow }
     * 
     */
    public InvokeIntalioQCFlow createInvokeIntalioQCFlow() {
        return new InvokeIntalioQCFlow();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.mediasmiths.foxtel.ip.common.events/001/000", name = "failureParameter", scope = AutoQCErrorNotification.class)
    public JAXBElement<String> createAutoQCErrorNotificationFailureParameter(String value) {
        return new JAXBElement<String>(_AutoQCErrorNotificationFailureParameter_QNAME, String.class, AutoQCErrorNotification.class, value);
    }

}
