//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 01:44:29 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.mediasmiths.foxtel.ip.common.events/001/000", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package events.common.ip.foxtel.mediasmiths.com._001._000;
