//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 01:44:29 PM BST 
//


package events.common.ip.foxtel.mediasmiths.com._001._000;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreviewStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PreviewStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PreviewFailed"/>
 *     &lt;enumeration value="PreviewFurtherAnalysis"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PreviewStatus")
@XmlEnum
public enum PreviewStatus {

    @XmlEnumValue("PreviewFailed")
    PREVIEW_FAILED("PreviewFailed"),
    @XmlEnumValue("PreviewFurtherAnalysis")
    PREVIEW_FURTHER_ANALYSIS("PreviewFurtherAnalysis");
    private final String value;

    PreviewStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PreviewStatus fromValue(String v) {
        for (PreviewStatus c: PreviewStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
