//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 01:44:29 PM BST 
//


package events.common.ip.foxtel.mediasmiths.com._001._000;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Used to track purge related activity for reporting
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://com.mediasmiths.foxtel.ip.common.events/001/000}IPEvent">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="titleId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="materialId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *         &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assetType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="purged" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="protected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="extended" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasPurgeCandidateTask" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="purgeCandidateCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="purgeCandidateUpdated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="expires" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titleId",
    "materialId",
    "houseId",
    "assetType",
    "purged",
    "_protected",
    "extended",
    "hasPurgeCandidateTask",
    "purgeCandidateCreated",
    "purgeCandidateUpdated",
    "expires"
})
@XmlRootElement(name = "PurgeEventNotification")
public class PurgeEventNotification
    extends IPEvent
{

    protected String titleId;
    protected String materialId;
    @XmlElement(required = true)
    protected String houseId;
    @XmlElement(required = true)
    protected String assetType;
    protected boolean purged;
    @XmlElement(name = "protected")
    protected boolean _protected;
    protected boolean extended;
    protected boolean hasPurgeCandidateTask;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar purgeCandidateCreated;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar purgeCandidateUpdated;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expires;

    /**
     * Gets the value of the titleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleId() {
        return titleId;
    }

    /**
     * Sets the value of the titleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleId(String value) {
        this.titleId = value;
    }

    /**
     * Gets the value of the materialId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialId() {
        return materialId;
    }

    /**
     * Sets the value of the materialId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialId(String value) {
        this.materialId = value;
    }

    /**
     * Gets the value of the houseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseId() {
        return houseId;
    }

    /**
     * Sets the value of the houseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseId(String value) {
        this.houseId = value;
    }

    /**
     * Gets the value of the assetType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetType() {
        return assetType;
    }

    /**
     * Sets the value of the assetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetType(String value) {
        this.assetType = value;
    }

    /**
     * Gets the value of the purged property.
     * 
     */
    public boolean isPurged() {
        return purged;
    }

    /**
     * Sets the value of the purged property.
     * 
     */
    public void setPurged(boolean value) {
        this.purged = value;
    }

    /**
     * Gets the value of the protected property.
     * 
     */
    public boolean isProtected() {
        return _protected;
    }

    /**
     * Sets the value of the protected property.
     * 
     */
    public void setProtected(boolean value) {
        this._protected = value;
    }

    /**
     * Gets the value of the extended property.
     * 
     */
    public boolean isExtended() {
        return extended;
    }

    /**
     * Sets the value of the extended property.
     * 
     */
    public void setExtended(boolean value) {
        this.extended = value;
    }

    /**
     * Gets the value of the hasPurgeCandidateTask property.
     * 
     */
    public boolean isHasPurgeCandidateTask() {
        return hasPurgeCandidateTask;
    }

    /**
     * Sets the value of the hasPurgeCandidateTask property.
     * 
     */
    public void setHasPurgeCandidateTask(boolean value) {
        this.hasPurgeCandidateTask = value;
    }

    /**
     * Gets the value of the purgeCandidateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPurgeCandidateCreated() {
        return purgeCandidateCreated;
    }

    /**
     * Sets the value of the purgeCandidateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPurgeCandidateCreated(XMLGregorianCalendar value) {
        this.purgeCandidateCreated = value;
    }

    /**
     * Gets the value of the purgeCandidateUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPurgeCandidateUpdated() {
        return purgeCandidateUpdated;
    }

    /**
     * Sets the value of the purgeCandidateUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPurgeCandidateUpdated(XMLGregorianCalendar value) {
        this.purgeCandidateUpdated = value;
    }

    /**
     * Gets the value of the expires property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpires() {
        return expires;
    }

    /**
     * Sets the value of the expires property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpires(XMLGregorianCalendar value) {
        this.expires = value;
    }

}
