//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 01:44:29 PM BST 
//


package events.common.ip.foxtel.mediasmiths.com._001._000;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://com.mediasmiths.foxtel.ip.common.events/001/000}IPEvent">
 *       &lt;sequence>
 *         &lt;element name="fileSystemReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="megaBytesUsed" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="megaBytesFree" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileSystemReference",
    "megaBytesUsed",
    "megaBytesFree"
})
@XmlRootElement(name = "StorageUsageDetails")
public class StorageUsageDetails
    extends IPEvent
{

    @XmlElement(required = true)
    protected String fileSystemReference;
    protected double megaBytesUsed;
    protected double megaBytesFree;

    /**
     * Gets the value of the fileSystemReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileSystemReference() {
        return fileSystemReference;
    }

    /**
     * Sets the value of the fileSystemReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileSystemReference(String value) {
        this.fileSystemReference = value;
    }

    /**
     * Gets the value of the megaBytesUsed property.
     * 
     */
    public double getMegaBytesUsed() {
        return megaBytesUsed;
    }

    /**
     * Sets the value of the megaBytesUsed property.
     * 
     */
    public void setMegaBytesUsed(double value) {
        this.megaBytesUsed = value;
    }

    /**
     * Gets the value of the megaBytesFree property.
     * 
     */
    public double getMegaBytesFree() {
        return megaBytesFree;
    }

    /**
     * Sets the value of the megaBytesFree property.
     * 
     */
    public void setMegaBytesFree(double value) {
        this.megaBytesFree = value;
    }

}
