package com.mediasmiths.foxtel.placeholder;

public enum PlaceHolderMessageValidationResult {
		IS_VALID,
		FAILS_XSD_CHECK,
		FAILED_TO_UNMARSHALL,	
		UNEXPECTED_TYPE,
		ACTIONS_ELEMENT_CONTAINED_MUTIPLE_ACTIONS,
		INVALID_MESSAGE_ID,
		INVALID_SENDER_ID,
		INVALID_PRIVATE_MESSAGE_DATA,
		INVALID_ACTIONS,
		
		
		NO_EXISTING_TITLE_FOR_MATERIAL,
		NO_EXISTING_MATERIAL_FOR_PACKAGE,
		TITLE_IDS_IN_TITLE_AND_MEDIA_DO_NOT_MATCH,
		LICENCE_DATES_NOT_IN_ORDER,
		TARGET_DATE_AND_REQUIREDBY_DATES_NOT_IN_ORDER,
		ORDER_CREATED_AND_REQUIREDBY_DATES_NOT_IN_ORDER,
		PACKAGE_FOR_REQUESTED_DELETE_MATERIAL_IN_REQUEST,
		MATERIAL_FOR_REQUESTED_DELETE_TITLE_IN_REQUEST,
		UNKOWN_VALIDATION_FAILURE;

}
