package com.mediasmiths.foxtel.ip.mayam.pdp;

public enum PDPErrorCodes {
	NOT_AUTHORIZED,
	TECHNICAL_FAULT,
	MEDIA_MISSING, 
	SEGMENT_NUMBER_MISMATCH, 
	CLASSIFICATION_FAILURE, 
	PROTECTED, 
	TASK_ALREADY_EXISTS, 
	COMPILE_FLAG_NOT_SET
}
