package com.mediasmiths.foxtel.ip.mayam.pdp;

public enum PrivilegedOperations
{
	PROTECT,
	UNPROTECT,
	DELETE,
	AUTOQC,
	INGEST,
	UNINGEST,
	COMPLIANCE_LOGGING,
	COMPLIANCE_EDITING,
	MATCHING,
	PREVIEW,
	TX_DELIVERY,
	EXPORT_MARKERS,
	COMPLIANCE_PROXY,
	CAPTIONS_PROXY,
	PUBLICITY_PROXY,
	FILEVERIFYOVERRIDE,
	QCPARALLEL,
	SEGMENT_MISMATCH_OVERRIDE
}
