<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://mamwkf01.mam.foxtel.com.au:8080/fx-WFAdapter/rest/wf/tx/autoQCRequired?packageID={packageID}" ID="_KAXAACgBEeKqjLVbpvrXug">
  <rest:operation verb="GET" name="autoQcRequired" ID="_KAXAAigBEeKqjLVbpvrXug">
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}boolean" name="autoQCRequired" headerDirection="request" contentType="text/plain" ID="_KAXAAygBEeKqjLVbpvrXug"/>
  </rest:operation>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="packageID" headerDirection="request" contentType="text/xml" ID="_KAXAASgBEeKqjLVbpvrXug"/>
</rest:descriptor>