#!/bin/sh
### BEGIN INIT INFO
# Provides:          mule
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mule standalone
# Description:       Launches mule
### END INIT INFO

MULE_HOME=/opt/ipwf/applications/mule-enterprise-standalone-3.3.1
MULE_USER=sysadmin

JAVA_HOME=/opt/java/jdk1.7.0_09
PATH=/sbin:/usr/sbin:/bin:/usr/bin:$JAVA_HOME/bin

case $1 in
start|stop|restart|status)
	# pass arg 1 onto mule script
	exec sudo -u $MULE_USER env JAVA_HOME=$JAVA_HOME PATH=$PATH $MULE_HOME/bin/mule $1
	;;
force-reload)
	# perform a restart
	exec sudo -u $MULE_USER env JAVA_HOME=$JAVA_HOME PATH=$PATH $MULE_HOME/bin/mule restart
	;;
esac




