#!/bin/sh
### BEGIN INIT INFO
# Provides:          tomcat
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Apache Tomcat Launcher
# Description:       Launches tomcat
### END INIT INFO

# Author: Peter Wright
#
# Updated : 29/04/13 Bryce Mcleod
#			- Refuse to start if this machine does not own the configured virtual ip
#           - When stopping be polite at first (call stop.sh) wait a while, if tomcat hasn't stopped then don't be so polite (call kill.sh)
#

VIRTUAL_IP="10.111.224.213"
VIRTUAL_IP_DEVICE="bond0"

LOG_FILE="/var/log/mediasmiths/tomcatservice.log"

export TOMCAT_DIR="/opt/ipwf/applications/apache-tomcat-7.0.32"
export JAVA_HOME=/opt/java/jdk1.7.0_09

# Do NOT "set -e"
# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin:$JAVA_HOME/bin

case "$1" in
  debug)
	exec "$TOMCAT_DIR/bin/debug.sh"
	;;
  start)
  
	#check if we own the virtual ip address for the service
	ifconfig ${VIRTUAL_IP_DEVICE} | grep "inet ${VIRTUAL_IP}" > /dev/null		
	#return code from grep will be zero if the address is present in the output of ifconfig [device]
  	
  	if [ $? -gt 0 ];
  	then
  		echo $(date) "- I don't seem to own the address ${VIRTUAL_IP} on device ${VIRTUAL_IP_DEVICE}, cowardly refusing to start" | tee -a ${LOG_FILE}
  		exit 1
  	else  
		exec "$TOMCAT_DIR/bin/start.sh"
	fi
	
	;;
	restart|force-reload)
		exec "$TOMCAT_DIR/bin/start.sh"
	;;
  stop)
  
  	#Be polite at first
	echo "Asking tomcat to stop"
	$TOMCAT_DIR/bin/stop.sh
	echo "Waiting a short while"
	sleep 5

	#We should have shut down gracefully by now, lets check
	$TOMCAT_DIR/bin/status.sh
	
	if [ $? -eq 0 ];
	then
		#Tomcat failed to shut down, kill it. Not ideal but tomcat needs to be stopped at the end of this process
		echo $(date) "- Tomcat failed to stop gracefully...killing" | tee -a ${LOG_FILE}
		exec "$TOMCAT_DIR/bin/kill.sh"
	else
		echo "Tomcat stopped"
	fi
	
	;;
  kill)
	exec "$TOMCAT_DIR/bin/kill.sh"
	;;
  status)
	# N.B. HA-Linux Heartbeat expects to see "OK" or "running" if a service is running.
	# If it sees this anywhere in the output (for example, "Tomcat is not running") it will
	# assume the service is running. 
	exec $TOMCAT_DIR/bin/status.sh
	;;
  *)
	echo "Usage: $SCRIPTNAME {debug|start|stop|kill|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
