package com.mediasmiths.foxtel.agent.validation;

public enum MessageValidationResult {
	IS_VALID, 
	FAILS_XSD_CHECK, 
	FAILED_TO_UNMARSHALL, 
	UNEXPECTED_TYPE, 
	ACTIONS_ELEMENT_CONTAINED_MUTIPLE_ACTIONS, 
	//invalid message id may be returned if the receipt for a given message already exists (ie the messageid could be a duplicate)
	INVALID_MESSAGE_ID, INVALID_SENDER_ID, INVALID_PRIVATE_MESSAGE_DATA, NO_EXISTING_TITLE_FOR_MATERIAL, NO_EXISTING_MATERIAL_FOR_PACKAGE, LICENCE_DATES_NOT_IN_ORDER, ORDER_CREATED_AND_REQUIREDBY_DATES_NOT_IN_ORDER, PACKAGES_MATERIAL_IS_PROTECTED, UNKOWN_VALIDATION_FAILURE, TITLE_OR_DESCENDANT_IS_PROTECTED, MAYAM_CLIENT_ERROR;

}
