//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.31 at 09:15:36 AM GMT 
//
package com.mediasmiths.stdEvents.events.db.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

import com.mediasmiths.stdEvents.coreEntity.db.entity.EventEntity;
import com.mediasmiths.stdEvents.events.db.entity.HibernateEventingMessage;


/**
 * This abstract type defines the basic elements, attributes, and format for material information. It's used as a base for more concrete definitions of material such as programme material.
 * 
 * <p>Java class for materialType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="materialType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AdultMaterial" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Format" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}formatEnumType"/>
 *         &lt;element name="AspectRatio" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}aspectRatioEnumType"/>
 *         &lt;element name="FirstFrameTimecode" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}timecodeType"/>
 *         &lt;element name="LastFrameTimecode" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}timecodeType"/>
 *         &lt;element name="Duration" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}timecodeType"/>
 *         &lt;element name="Media" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}mediaType"/>
 *         &lt;element name="AudioTracks">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Track" maxOccurs="8">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TrackNumber">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                                   &lt;totalDigits value="1"/>
 *                                   &lt;minInclusive value="1"/>
 *                                   &lt;maxInclusive value="8"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TrackEncoding" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}audioEncodingEnumType"/>
 *                             &lt;element name="TrackName" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}audioTrackEnumType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@Entity
@Table(name="contentPickup")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name="ContentPickup")
public class ContentPickup extends HibernateEventingMessage
{
	@Id
	@GeneratedValue(generator="gen")
    @GenericGenerator(name="gen", strategy="foreign", parameters=@Parameter(name="property", value="event"))
	Long materialTypeId;
	
	@Column(name="adult_material")
    @XmlElement(name = "AdultMaterial")
    public boolean adultMaterial;
	
	@Column(name="format")
    @XmlElement(name = "Format", required = true)
    public String format;
	
	@Column(name="aspect_ratio")
    @XmlElement(name = "AspectRatio", required = true)
    public String aspectRatio;
    
	@Column(name="first_frame_timecode")
    @XmlElement(name = "FirstFrameTimecode", required = true)
    public String firstFrameTimecode;
    
	@Column(name="last_frame_timecode")
    @XmlElement(name = "LastFrameTimecode", required = true)
    public String lastFrameTimecode;
   
	@Column(name="duration")
    @XmlElement(name = "Duration", required = true)
    public String duration;
    
	@Column(name="media")
	@Type(type="text")
    @XmlElement(name = "Media", required = true)
    public String media;
	
	@Column(name="original_conform")
	@XmlElement(name = "OriginalConform")
	@Lob
    protected String originalConform;
	
	@Column(name="presentation")
	@XmlElement(name = "Presentation")
	@Lob
    protected String presentation;

	@Column(name="additional_program_detail")
	@XmlElement(name = "AdditionalProgrammeDetail")
	@Lob
    protected String additionalProgrammeDetail;
	
	@Column(name="material_id")
	@XmlElement
    protected String materialID;
	
	@Column(name="unmatched_path")
	@XmlElement
	public String unmatchedPath;
	
	@OneToOne
	@PrimaryKeyJoinColumn
	public EventEntity event;

    /**
     * Gets the value of the adultMaterial property.
     * 
     */
    public boolean isAdultMaterial() {
        return adultMaterial;
    }

    /**
     * Sets the value of the adultMaterial property.
     * 
     */
    public void setAdultMaterial(boolean value) {
        this.adultMaterial = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the aspectRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAspectRatio() {
        return aspectRatio;
    }

    /**
     * Sets the value of the aspectRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAspectRatio(String value) {
        this.aspectRatio = value;
    }

    /**
     * Gets the value of the firstFrameTimecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstFrameTimecode() {
        return firstFrameTimecode;
    }

    /**
     * Sets the value of the firstFrameTimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstFrameTimecode(String value) {
        this.firstFrameTimecode = value;
    }

    /**
     * Gets the value of the lastFrameTimecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastFrameTimecode() {
        return lastFrameTimecode;
    }

    /**
     * Sets the value of the lastFrameTimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastFrameTimecode(String value) {
        this.lastFrameTimecode = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the media property.
     * 
     * @return
     *     possible object is
     *     {@link MediaType }
     *     
     */
    public String getMedia() {
        return media;
    }

    /**
     * Sets the value of the media property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaType }
     *     
     */
    public void setMedia(String value) {
        this.media = value;
    }
    
    public String getOriginalConform()
	{
		return originalConform;
	}

	public void setOriginalConform(String originalConform)
	{
		this.originalConform = originalConform;
	}

	public String getPresentation()
	{
		return presentation;
	}

	public void setPresentation(String presentation)
	{
		this.presentation = presentation;
	}

	public String getAdditionalProgrammeDetail()
	{
		return additionalProgrammeDetail;
	}

	public void setAdditionalProgrammeDetail(String additionalProgrammeDetail)
	{
		this.additionalProgrammeDetail = additionalProgrammeDetail;
	}

	public String getMaterialID()
	{
		return materialID;
	}

	public void setMaterialID(String materialID)
	{
		this.materialID = materialID;
	}

	public String getUnmatchedPath()
	{
		return unmatchedPath;
	}

	public void setUnmatchedPath(String unmatchedPath)
	{
		this.unmatchedPath = unmatchedPath;
	}

    /**
     * Gets the value of the audioTracks property.
     * 
     * @return
     *     possible object is
     *     {@link MaterialType.AudioTracks }
     *     
     */
    /*public MaterialType.AudioTracks getAudioTracks() {
        return audioTracks;
    }

    *//**
     * Sets the value of the audioTracks property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaterialType.AudioTracks }
     *     
     *//*
    public void setAudioTracks(MaterialType.AudioTracks value) {
        this.audioTracks = value;
    }*/


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Track" maxOccurs="8">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TrackNumber">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *                         &lt;totalDigits value="1"/>
     *                         &lt;minInclusive value="1"/>
     *                         &lt;maxInclusive value="8"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TrackEncoding" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}audioEncodingEnumType"/>
     *                   &lt;element name="TrackName" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}audioTrackEnumType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
   /* @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "track"
    })
    public static class AudioTracks {

        @XmlElement(name = "Track", required = true)
        protected List<MaterialType.AudioTracks.Track> track;

        *//**
         * Gets the value of the track property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the track property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTrack().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MaterialType.AudioTracks.Track }
         * 
         * 
         *//*
        public List<MaterialType.AudioTracks.Track> getTrack() {
            if (track == null) {
                track = new ArrayList<MaterialType.AudioTracks.Track>();
            }
            return this.track;
        }


        *//**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TrackNumber">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
         *               &lt;totalDigits value="1"/>
         *               &lt;minInclusive value="1"/>
         *               &lt;maxInclusive value="8"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TrackEncoding" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}audioEncodingEnumType"/>
         *         &lt;element name="TrackName" type="{http://foxtel.tv/engineering/broadcast/schemas/2/0/mediaExchange}audioTrackEnumType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         *//*
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "trackNumber",
            "trackEncoding",
            "trackName"
        })
        public static class Track {

            @XmlElement(name = "TrackNumber")
            protected int trackNumber;
            @XmlElement(name = "TrackEncoding", required = true)
            protected String trackEncoding;
            @XmlElement(name = "TrackName", required = true)
            protected String trackName;

            *//**
             * Gets the value of the trackNumber property.
             * 
             *//*
            public int getTrackNumber() {
                return trackNumber;
            }

            *//**
             * Sets the value of the trackNumber property.
             * 
             *//*
            public void setTrackNumber(int value) {
                this.trackNumber = value;
            }

            *//**
             * Gets the value of the trackEncoding property.
             * 
             * @return
             *     possible object is
             *     {@link AudioEncodingEnumType }
             *     
             *//*
            public String getTrackEncoding() {
                return trackEncoding;
            }

            *//**
             * Sets the value of the trackEncoding property.
             * 
             * @param value
             *     allowed object is
             *     {@link AudioEncodingEnumType }
             *     
             *//*
            public void setTrackEncoding(String value) {
                this.trackEncoding = value;
            }

            *//**
             * Gets the value of the trackName property.
             * 
             * @return
             *     possible object is
             *     {@link AudioTrackEnumType }
             *     
             *//*
            public String getTrackName() {
                return trackName;
            }

            *//**
             * Sets the value of the trackName property.
             * 
             * @param value
             *     allowed object is
             *     {@link AudioTrackEnumType }
             *     
             *//*
            public void setTrackName(String value) {
                this.trackName = value;
            }

        }

    }*/

}
