<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://mamwfe-pkg.mam.foxtel.com.au:8080/fx-WFAdapter/rest/wf/export/failed" ID="_NV2FoMOzEeK-A9uoUuxK3w">
  <rest:operation verb="POST" name="exportFailed" ID="_NV2FocOzEeK-A9uoUuxK3w">
    <rest:input type="project:///wfAdapter/wfAdapter.xsd?xsdelement={http://ns.mediasmiths.com/foxtel/wf/adapter}exportFailedRequest" name="body" headerDirection="request" contentType="application/xml" ID="_NV2FosOzEeK-A9uoUuxK3w"/>
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}anyType" name="response" headerDirection="request" contentType="application/xml" ID="_NV2Fo8OzEeK-A9uoUuxK3w"/>
  </rest:operation>
</rest:descriptor>