<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://mamwkf01.mam.foxtel.com.au:8082/fx-WFAdapter/rest/wf/tc/tcFailed" ID="__uLrQCHOEeKyysgOm3-sfQ">
  <rest:operation verb="PUT" name="tcFailure" ID="__uLrRiHOEeKyysgOm3-sfQ">
    <rest:input type="project:///wfAdapter/wfAdapter.xsd?xsdelement={http://ns.mediasmiths.com/foxtel/wf/adapter}tcFailureNotification" name="body" headerDirection="request" contentType="application/xml" ID="__uLrRyHOEeKyysgOm3-sfQ"/>
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}anyType" name="response" headerDirection="request" contentType="text/plain" ID="__uLrSCHOEeKyysgOm3-sfQ"/>
  </rest:operation>
</rest:descriptor>