<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://10.111.224.213:8080/fx-WFAdapter/rest/wf/tx/delivery/writeSegmentXML?packageID={packageID}" ID="_iI2NcCjGEeK0LJoN9o-OZw">
  <rest:operation verb="GET" name="writeSegmentXML" ID="_iI2NcSjGEeK0LJoN9o-OZw">
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="response" headerDirection="request" contentType="text/plain" ID="_iI2NcijGEeK0LJoN9o-OZw"/>
  </rest:operation>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="packageID" headerDirection="request" contentType="text/xml" ID="_lihfACjGEeK0LJoN9o-OZw"/>
</rest:descriptor>