<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://10.111.224.213:8080/fx-qcAdapter/rest/qc/job/{jobname}/result" ID="_rrEh8GxvEeK85v-SsU5zfw">
  <rest:operation verb="GET" name="getJobResult" ID="_rrEh8mxvEeK85v-SsU5zfw">
    <rest:output type="project:///qcAdapterRest/qcAdapter.xsd?xsdelement={http://ns.mediasmiths.com/foxtel/qc/adapter}qcJobResult" name="response" headerDirection="request" contentType="application/xml" ID="_rrEh82xvEeK85v-SsU5zfw"/>
    <rest:fault type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}anyType" name="fault" headerDirection="request" contentType="text/html" ID="_FH95MHH5EeKofd0UxythbA"/>
  </rest:operation>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="jobname" headerDirection="request" contentType="text/xml" ID="_rrEh8WxvEeK85v-SsU5zfw"/>
</rest:descriptor>