<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://mamwfe-pkg.mam.foxtel.com.au:8080/fx-qcAdapter/rest/qc/start" ID="_MG3IYBa8EeKqpuzjrTcpXg">
  <rest:operation verb="PUT" name="qcStart" ID="_MG3IYRa8EeKqpuzjrTcpXg">
    <rest:input type="project:///qcAdapterRest/qcAdapter.xsd?xsdelement={http://ns.mediasmiths.com/foxtel/qc/adapter}qcStartRequest" name="body" headerDirection="request" contentType="application/xml" ID="_MG3IYha8EeKqpuzjrTcpXg"/>
    <rest:output type="project:///qcAdapterRest/qcAdapter.xsd?xsdelement={http://ns.mediasmiths.com/foxtel/qc/adapter}qcStartResponse" name="response" headerDirection="request" contentType="application/xml" ID="_MG3IYxa8EeKqpuzjrTcpXg"/>
    <rest:fault type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}anyType" name="fault" headerDirection="request" contentType="text/html" ID="_5pzz0HH4EeKofd0UxythbA"/>
  </rest:operation>
</rest:descriptor>